name: dmdc-pipeline
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - librosa
  - glob2
  - ffmpeg
  - libsndfile
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - yt-dlp
      - mediapipe
      - pyannote.audio
      - pyannote.core
      - pyannote.database
      - pyannote.metrics
      - pyannote.pipeline
      - pydub
      - moviepy
      - tqdm
      - opencv-python
      - ffmpeg-python
      - scikit-learn
      - soundfile
      
